config/routes.rb
Rails.application.routes.draw do
  get 'posts/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'root#top'

  get '/top' => 'root#top'

  post '/posts' => 'posts#create'

  get '/posts/:id' => 'posts#show', as: 'post'

  get '/posts/:id/edit' => 'posts#edit', as: 'edit_post'

  patch '/posts/:id' => 'posts#update', as: 'update_post'

  delete '/posts/:id' => 'posts#destroy', as: 'destroy_post'

  post '/posts/:id' => 'posts#update'

  post '/posts/:id' => 'posts#save'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  	@post = Post.new
  	@posts = Post.all
  end

  def create
  	  post = Post.new(post_params)
   if post.save
      flash[:notice] = "Book was successfully created"
  	  redirect_to post_path(post.id)
   end
  end

  def index
  	  @posts = Post.all
  end

  def show
  	  @post = Post.find(params[:id])
  end

  def edit
  	  @post = Post.find(params[:id])
  end

  def update
  	  post = Post.find(params[:id])
   if post.update(post_params)
      flash[:notice] = "Book was successfully updated"
  	  redirect_to post_path(post.id)
   end
  end

  def destroy
  	  post = Post.find(params[:id])
  	  post.destroy
  	  redirect_to posts_new_path
  end

  private

  def post_params
  	  params.require(:post).permit(:title, :body)
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Editing Book</h1>
<!-- form_for部分 -->
<%= form_for(@post) do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title, class: "book_title" %>
    <h4>Body</h4>
    <%= f.text_area :body, class: "book_body" %>
    <p class="submit"><%= f.submit 'Update Book' %></p>
<% end %>
<span class="under"><%= link_to "Show", post_path(@post.id), class: "show" %></span>|
<span class="under"><%= link_to 'Back', posts_new_path, class: "back" %></span>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html>

<head>
	<title>Bookers</title>
</head>

<body>

	<h1>Books</h1>

	<table>
		<thead>
			<tr>
				<th>Title</th>
				<th>Body</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @posts.each do |post| %>
			<tr>
				<td>
					<span class="indent"><%= post.title %></span>
				</td>
				<td>
					<span class="indent"><%= post.body %></span>
				</td>
				<td class="white">
					<span class="under"><%= link_to "Show", post_path(post.id), class: "show_#{post.id}" %></span>
					<span class="under"><%= link_to "Edit", edit_post_path(post.id), class: "edit_#{post.id}" %></span>
					<span class="under"><%= link_to "Destroy", destroy_post_path(post.id), class: "destroy_#{post.id}", method: :delete, "data-confirm" => "Are you sure that you want to delete?" %></span>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>





	<h2>New book</h2>
	<!-- form_for部分 -->
	<%= form_for(@post) do |f| %>

	<h4>Title</h4>
	<%= f.text_field :title, class: "book_title" %>

	<h4>Body</h4>
	<%= f.text_area :body,class: "book_body" %>

	<p class="submit"><%= f.submit 'Create Book' %></p>

	<% end %>

</body>

</html>

app/views/posts/show.html.erb
<% if flash[:notice] %>
      <div class="flash">
        <span class="notice"><%= flash[:notice] %></span>
      </div>
    <% end %>

<p><strong class="show">Title:</strong><%= @post.title %></p>
<p><strong class="show">Body:</strong><%= @post.body %></p>


<%= link_to 'Edit', edit_post_path(@post.id), class: "edit" %> | <%= link_to 'Back', posts_new_path, class: "back" %>

app/views/root/top.html.erb
<h1 class="top_title">ようこそ <strong>Bookers</strong> へ！</h1>


<p>
	<strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や
</p>

<p>
	印象を共有し交換することができます
</p>

<p class="line">
	<%= link_to "start", posts_new_path %>
</p>